#include "custom.model.inc.h"
const GeoLayout Geo_ttm_1_0x4ebc60[]= {
GEO_NODE_SCREEN_AREA(10,160,120,160,120),
GEO_OPEN_NODE(),
GEO_ZBUFFER(0),
GEO_OPEN_NODE(),
GEO_NODE_ORTHO(100),
GEO_OPEN_NODE(),
GEO_BACKGROUND(0, geo_skybox_main),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_ZBUFFER(1),
GEO_OPEN_NODE(),
GEO_CAMERA_FRUSTUM_WITH_FUNC(45,100,12800, geo_camera_fov),
GEO_OPEN_NODE(),
GEO_CAMERA(1,0,2000,6000,0,63336,0, geo_camera_main),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(1,DL_ttm_1_0x700a120),
GEO_DISPLAY_LIST(1,DL_ttm_1_0x700a2e0),
GEO_RENDER_OBJ(),
GEO_ASM(0, geo_painting_update),
GEO_ASM(512, geo_painting_draw),
GEO_ASM(0, geo_movtex_pause_control),
GEO_ASM(13825, geo_movtex_draw_nocolor),
GEO_ASM(13826, geo_movtex_draw_nocolor),
GEO_ASM(13827, geo_movtex_draw_nocolor),
GEO_ASM(13828, geo_movtex_draw_nocolor),
GEO_ASM(13829, geo_movtex_draw_nocolor),
GEO_ASM(13825, geo_movtex_draw_water_regions),
GEO_ASM(0, geo_envfx_main),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_ZBUFFER(0),
GEO_OPEN_NODE(),
GEO_ASM(0, geo_cannon_circle_base),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};
